FORMAS_PAGAMENTO = ["PIX", "CARTAO_CREDITO", "CARTAO_DEBITO", "DINHEIRO"]

CANAIS = ["APP", "TOTEM", "BALCAO", "PICKUP", "WEB"]

STATUS = [ "AGUARDANDO_PAGAMENTO", "EM_PREPARACAO", "PRONTO", "ENTREGUE", "CANCELADO"]

OPERACOES = ["ENTRADA", "AJUSTE"]

PONTOS_POR_REAL = 1